version: '3.9'

name: devops-premade

services:
  rabbitmq1:
    image: bitnami/rabbitmq:3.13.3-debian-12-r0
    networks: ['rabbitmq_net']
    user: '0:0'
    environment:
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_ERL_COOKIE=secretcookie
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq1
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
    volumes:
      - ${CACHE_DIR:-./cache}/volumes/rabbitmq1:/bitnami/rabbitmq
      - ./enabled_plugins.conf:/etc/rabbitmq/enabled_plugins
    ports:
      - '15672:15672' # Management console
      - '5672:5672' # RabbitMQ port
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      start_interval: 30s
      interval: 30s
      timeout: 20s
      retries: 9

  rabbitmq2:
    image: bitnami/rabbitmq:3.13.3-debian-12-r0
    networks: ['rabbitmq_net']
    user: '0:0'
    environment:
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_ERL_COOKIE=secretcookie
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq2
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@rabbitmq1
    volumes:
      - ${CACHE_DIR:-./cache}/volumes/rabbitmq2:/bitnami/rabbitmq
      - ./enabled_plugins.conf:/etc/rabbitmq/enabled_plugins
    ports:
      - '15673:15672' # Management console
      - '5673:5672' # RabbitMQ port
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      start_interval: 30s
      interval: 30s
      timeout: 20s
      retries: 9
    depends_on:
      rabbitmq1:
        condition: service_healthy
        required: true
        restart: true

  rabbitmq3:
    image: bitnami/rabbitmq:3.13.3-debian-12-r0
    networks: ['rabbitmq_net']
    user: '0:0'
    environment:
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_ERL_COOKIE=secretcookie
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq3
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@rabbitmq1
    volumes:
      - ${CACHE_DIR:-./cache}/volumes/rabbitmq3:/bitnami/rabbitmq
      - ./enabled_plugins.conf:/etc/rabbitmq/enabled_plugins
    ports:
      - '15674:15672' # Management console
      - '5674:5672' # RabbitMQ port
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      start_interval: 30s
      interval: 30s
      timeout: 20s
      retries: 9
    depends_on:
      rabbitmq2:
        condition: service_healthy
        required: true
        restart: true

networks:
  rabbitmq_net:
    driver: bridge
